-- Encuesta SUS (System Usability Scale)
-- Ejecutar: python scripts/aplicar_migracion_09_usabilidad.py

USE mtto_equipos;

CREATE TABLE IF NOT EXISTS usabilidad_encuestas (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  q1 TINYINT UNSIGNED NOT NULL,
  q2 TINYINT UNSIGNED NOT NULL,
  q3 TINYINT UNSIGNED NOT NULL,
  q4 TINYINT UNSIGNED NOT NULL,
  q5 TINYINT UNSIGNED NOT NULL,
  q6 TINYINT UNSIGNED NOT NULL,
  q7 TINYINT UNSIGNED NOT NULL,
  q8 TINYINT UNSIGNED NOT NULL,
  q9 TINYINT UNSIGNED NOT NULL,
  q10 TINYINT UNSIGNED NOT NULL,
  score DECIMAL(5,2) NOT NULL COMMENT 'SUS 0-100',
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_usabilidad_user (user_id),
  CONSTRAINT fk_usabilidad_user FOREIGN KEY (user_id) REFERENCES usuarios (id) ON DELETE CASCADE,
  CONSTRAINT chk_usabilidad_q1 CHECK (q1 BETWEEN 1 AND 5),
  CONSTRAINT chk_usabilidad_q2 CHECK (q2 BETWEEN 1 AND 5),
  CONSTRAINT chk_usabilidad_q3 CHECK (q3 BETWEEN 1 AND 5),
  CONSTRAINT chk_usabilidad_q4 CHECK (q4 BETWEEN 1 AND 5),
  CONSTRAINT chk_usabilidad_q5 CHECK (q5 BETWEEN 1 AND 5),
  CONSTRAINT chk_usabilidad_q6 CHECK (q6 BETWEEN 1 AND 5),
  CONSTRAINT chk_usabilidad_q7 CHECK (q7 BETWEEN 1 AND 5),
  CONSTRAINT chk_usabilidad_q8 CHECK (q8 BETWEEN 1 AND 5),
  CONSTRAINT chk_usabilidad_q9 CHECK (q9 BETWEEN 1 AND 5),
  CONSTRAINT chk_usabilidad_q10 CHECK (q10 BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
